export const projects = [
  {
    title: 'Climbing project',
    description: "Using Symfony, SQL. You can search on a map for all the different climbing sites in France, find tips and training exercises for climbing as well as news from the best current climbers.",
      image: '/images/imgEscal.png',
      tags: ['Symfony', 'SQL', 'Bootstrap', 'jQuery'],
    source: 'https://sediriger.com',
    visit: 'https://github.com/DiegoMarck/ProjetEscaladeNext',
    id: 0,
  },
  {
    title: 'Vesco',
    description:"This course from Udemy is about Building a Modern Responsive Website with HTML5, CSS3, Bootstrap, and some jQuery. In this course, you will learn how to Build a Modern Looking Responsive Website with modern web development technologies like HTML5, CSS3, Bootstrap, and some jQuery from scratch.",
    image: '/images/vesco.png',
    tags: ['Bootstrap', 'jQuery'],
    source: 'https://vesco.sediriger.com/',
    visit: 'https://github.com/DiegoMarck/Vesco',
    id: 1,
  },
  {
    title: 'Les Mondes Fantastiques',
    description: "This is a school project to learn javascript. You can find inside a slider menu, a mini gallery with a magnifying glass on the image, a top-panel and an accordeon.",
      image: '/images/LesMondesFantastiques.png',
      tags: ['CSS', 'Javascript'],
    source: 'https://lesmondesfanstastiques.sediriger.com',
    visit: 'https://github.com/DiegoMarck/Les-Mondes-Fantastiques',
    id: 2,
  },
  {
    title: 'Contact Form',
    description: "This is a simple contact form, build in HTML, CSS, PHP and Javascript. It's on Udemy in \"Formation Complète Développeur Web\" from John Taieb.",
    image: '/images/form.png',
    tags: ['HTML', 'CSS', 'PHP', 'Javascript'],
    source: 'https://form.sediriger.com/',
    visit: 'https://github.com/DiegoMarck/ContactForm--with-recaptcha',
    id: 3,
  },
  {
    title: 'Personal CV',
    description: "This is a website with the transcription of my personal CV in HTML and CSS and a little bit of PHP. I bought it on Udemy. It's from John Taieb.",
    image: '/images/cv.png',
    tags: ['HTML', 'CSS', 'PHP'],
    source: 'https://cv.sediriger.com/',
    visit: 'https://github.com/DiegoMarck/CV_perso_dev',
    id: 3,
  },
  {
    title: 'Jeu du Serpent',
    description: "This is a website which allows to play to the Snake game, build in Javascript. I bought it on Udemy. It's from John Taieb.",
    image: '/images/jeuduserpent.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://jeuduserpent.sediriger.com/',
    visit: 'https://github.com/DiegoMarck/Jeu-du-Serpent',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Full stack web developer training at NextFormation', },
  { year: 2021, text: 'Web developer internship at Moneiot', },
  { year: 2021, text: 'Title of Full Stack Web Developer obtained', },
  { year: 2022, text: 'Web developer job at Aylo-Solutions', },
  { year: 2022, text: 'Started my portfolio project', },
  { year: 2023, text: 'Started my NetFlix Clone, work in progress', },
];